name: Every 2 minitssssss fb
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.3
        - name: Install
          run: npm install
        - name: Test
          run: npm run wdio
        - uses: actions/upload-artifact@v1
